# Generated by Django 4.0.4 on 2022-05-20 21:07

import datetime
import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='fname')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='lname')),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.DateField(default=datetime.date.today, validators=[students.validators.adult_validator])),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='stphnumber')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
