# Generated by Django 4.0.4 on 2022-05-27 12:41

import django.core.validators
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10), students.validators.uniqness_validator], verbose_name='st_ph_number'),
        ),
    ]
