# Generated by Django 4.0.4 on 2022-06-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
