# Generated by Django 4.0.4 on 2022-06-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_date_of_end'),
        ('students', '0006_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
