# Generated by Django 4.0.4 on 2022-05-20 21:07

import datetime
import django.core.validators
from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='teacherID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='t_fname')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='t_lname')),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.DateField(default=datetime.date.today, validators=[teachers.validators.adult_validator])),
                ('phone_number', models.CharField(default='', max_length=20, validators=[django.core.validators.MinLengthValidator(10), teachers.validators.uniqness_validator], verbose_name='t_ph_number')),
            ],
        ),
    ]
