# Generated by Django 4.0.4 on 2022-05-27 12:41

import django.core.validators
from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10), teachers.validators.uniqness_validator], verbose_name='t_ph_number'),
        ),
    ]
