# Generated by Django 4.0.4 on 2022-06-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
    ]
