# Generated by Django 4.0.4 on 2022-06-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_date_of_end'),
        ('teachers', '0005_remove_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.group'),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
