# Generated by Django 4.0.4 on 2022-06-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_date_of_end_alter_group_date_of_start'),
        ('teachers', '0006_teacher_group_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.group'),
        ),
    ]
