# Generated by Django 4.0.4 on 2022-06-09 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='course name')),
                ('duration', models.PositiveIntegerField(blank=True, verbose_name='course duration')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='course price')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
    ]
