# /home/user/PycharmProjects/DJANGO/DJANGO_LMS/teachers/views.py

from django.shortcuts import render
# from django.http import HttpResponse

from .models import Teacher
# from student.models import Student

from webargs.fields import Str, Int
from webargs.djangoparser import use_args, use_kwargs

@use_kwargs(
    {'cnt': Int(required=False)},
    location='query'
)
def generate_teachers(request, cnt=10, max_number = 100):

        if cnt == 10:
            Teacher.gen_teachers()
        else:
            Teacher.gen_teachers(cnt=cnt)
        return render(
            request,
            'generate_teachers.html',
            {'title': 'Generate teachers',
            'message01': f'Input the number of teachers (max = {max_number}) you wish to generate. 10 items generated by default.',
             'message02': f'{cnt} teacher(-s) has been generated. You can check it in a "../DJANGO_LMS/db.sqlite3" data base file in a "teachers_teacher" table',
             'max':max_number}
        )


