# Generated by Django 4.0.4 on 2022-06-07 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='groupID')),
                ('group_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='group name')),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='date of start')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='date of end')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'groups',
            },
        ),
    ]
