# Generated by Django 4.0.4 on 2022-05-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0, verbose_name='stds_num'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='groupID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='group_name'),
        ),
    ]
