# Generated by Django 4.0.4 on 2022-05-28 19:10

import django.core.validators
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_of_start',
            field=models.DateField(verbose_name='date of start'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_of_students',
            field=models.PositiveSmallIntegerField(null=True, validators=[groups.validators.max_student_number_validator], verbose_name='number of students'),
        ),
    ]
