# Generated by Django 4.0.4 on 2022-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_date_of_start_alter_group_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_of_end',
            field=models.DateField(null=True, verbose_name='date of end'),
        ),
    ]
