# Generated by Django 4.0.4 on 2022-06-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_date_of_end'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
