# Generated by Django 4.0.4 on 2022-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_of_end',
            field=models.DateField(blank=True, null=True, verbose_name='date of end'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_of_start',
            field=models.DateField(blank=True, null=True, verbose_name='date of start'),
        ),
    ]
