# Generated by Django 4.0.4 on 2022-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_date_of_end_alter_group_date_of_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_students',
        ),
        migrations.AddField(
            model_name='group',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
