# Generated by Django 4.0.4 on 2022-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_group_number_of_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
